---
# handlers file for bind

- name: restart-bind
  service:
    name: '{{ bind__service_name }}'
    state: restarted

- name: reload-bind
  service:
    name: '{{ bind__service_name }}'
    state: reloaded
